### ISSUE TITLE
Cannot install on alpine

### ISSUE THREAD

**Issue by NobodyXu** [r-lib/fs#210]
I am building this package using `R -e “install.packages(‘fs’)” on alpine 3.9 using edge mirror, with `automake 1.16` and `autoconf` installed and the process failed with the message below:

```
WARNING: 'automake-1.14' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make[2]: *** [Makefile:1081: Makefile.in] Error 1
make[2]: Leaving directory '/tmp/RtmpkffNGi/R.INSTALL18371bacba50/fs/src/libuv'
make[1]: *** [Makevars:38: libuv/.libs/libuv.a] Error 2
make[1]: Leaving directory '/tmp/RtmpkffNGi/R.INSTALL18371bacba50/fs/src'
ERROR: compilation failed for package ‘fs’
* removing ‘/usr/lib/R/library/fs’
cat: can't open 'usethis.out': No such file or directory
cat: can't open 'devtools.out': No such file or directory

The downloaded source packages are in
        ‘/tmp/RtmphPNKfa/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("devtools") :
  installation of one or more packages failed,
  probably ‘fs’, ‘usethis’, ‘devtools’
```

**Comment by lweehuizen-imb** [comment]
I encountered this too. It seems it's because Makevars does a touch of aclocal.m4, rather than executing aclocal (https://github.com/r-lib/fs/blob/00e2de80ca51182bcf27a3ded49192564c53c341/src/Makevars#L33)

Switch that code to run aclocal and automake, allows it to correctly compile on alpine.

Can somebody shed some light on the original intent on not running aclocal/automake?

**Comment by jimhester** [comment]
Re-running automake requires automake to be installed, which we do not actually need.

**Comment by klucar** [comment]
The build runs `src/fs/libuv/missing automake-1.14`

This makes the build fail if automake 1.14 isn't installed, even if it isn't run.

**Comment by AceHack** [comment]
What package do I need to install to make this work?

**Comment by AceHack** [comment]
This issue is blocking me from building the latest spark on alpine

**Comment by baank** [comment]
@jimhester  .. Is there an issue putting a dependency on automake ?

This issue blocks the use of R within Alpine.

**Comment by gitrc** [comment]
Could the maintainer of this project please provide an update?  This library is a dependency in numerous other packages and is blocking and breaking builds that rely upon it.  Thank you to @lweehuizen-imb for providing a temporary workaround.

**Comment by michalc** [comment]
I worked around this issue by installing automake 1.14 manually, as well as Perl 5.20 (since it looks like automake 1.14 won't install on Perl >= 5.22, and 5.21 is a development version). Below is a rough minimum Dockerfile for Alpine 2.8

```
FROM alpine:3.8

RUN \
	apk add --no-cache \
		autoconf \
		build-base \
		R \
		R-dev && \
	apk add --no-cache --virtual .build-deps \
		wget && \
	wget https://www.cpan.org/src/5.0/perl-5.20.3.tar.gz && \
	echo "3524e3a76b71650ab2f794fd68e45c366ec375786d2ad2dca767da424bbb9b4a  perl-5.20.3.tar.gz" | sha256sum -c && \
	tar -zxvf perl-5.20.3.tar.gz && \
	cd perl-5.20.3 && \
	./Configure -des && \
	make && \
	make install && \
	cd .. && \
	rm -r -f perl-5.20.3 && \
	wget https://ftp.gnu.org/gnu/automake/automake-1.14.1.tar.gz && \
	echo "814c2333f350ce00034a1fe718e0e4239998ceea7b0aff67e9fd273ed6dfc23b  automake-1.14.1.tar.gz" | sha256sum -c && \
	tar -zxvf automake-1.14.1.tar.gz && \
	rm -r -f automake-1.14.1.tar.gz && \
	cd automake-1.14.1 && \
	./configure && \
	make && \
	make install && \
	cd .. && \
	rm -r -f automake-1.14.1 && \
	apk del .build-deps

RUN \
	mkdir -p /usr/share/doc/R/html && \
	R -e 'install.packages("fs", repos="http://cran.rstudio.com")'
```

**Comment by gaborcsardi** [comment]
It would be great to fix this. It is quite strange that fs needs to run automake at install time.

**Comment by jimhester** [comment]
It doesn't run automake at install time

**Comment by gaborcsardi** [comment]
Right. Well, IDK what makes it re-run `autoconf` and `automake`, AFAICT Alpine ships the standard GNU tools.

FWIW, you could add `AM_MAINTAINER_MODE` in `configure.ac`, right after `AM_INIT_AUTOMAKE` and then it will never re-run them.

**Comment by gaborcsardi** [comment]
Another solution would be to leave out `configure.ac` and `Makefile.am` from the R package, they are surely not needed at installation time.

**Comment by jimhester** [comment]
This should be fixed after https://github.com/r-lib/fs/commit/7891357d42ed6b7334008aef8cc8497fc59aabab, I verified it by install R on alpine with

```r
FROM alpine:3.8

RUN \
	apk add --no-cache \
		autoconf \
		build-base \
		R \
		R-dev && \
	apk add --no-cache --virtual .build-deps \
		wget && \
	apk del .build-deps

RUN \
	mkdir -p /usr/share/doc/R/html
```

And building the package with those changes, so I believe it should now be fixed.

**Comment by gaborcsardi** [comment]
@jimhester Thanks! Hopefully it will not break anything else.

**Comment by gaborcsardi** [comment]
Btw. you don't need to add `autoconf`, now that Alpine is not running it.

**Comment by bamonroe** [comment]
Hi, thanks for all the work trying to get this sorted out, but I used the exact Dockerfile suggested in the December 18th post with an additional line to install the `fs` package and it still doesn't install throwing the same error about `automake` version 1.14:

```
Sending build context to Docker daemon  3.584kB

Step 1/4 : FROM alpine:3.8
 ---> dac705114996
Step 2/4 : RUN 	apk add --no-cache 		autoconf 		build-base 		R 		R-dev && 	apk add --no-cache --virtual .build-deps 		wget && 	apk del .build-deps
 ---> Using cache
 ---> eff52485080f
Step 3/4 : RUN 	mkdir -p /usr/share/doc/R/html
 ---> Using cache
 ---> f02e2fbe437b
Step 4/4 : RUN R -e "install.packages('fs', repos='https://cloud.r-project.org/')"
 ---> Running in 81b39bcecaca

R version 3.5.0 (2018-04-23) -- "Joy in Playing"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages('fs', repos='https://cloud.r-project.org/')
installing the dependency ‘Rcpp’

trying URL 'https://cloud.r-project.org/src/contrib/Rcpp_1.0.3.tar.gz'
Content type 'application/x-gzip' length 2749025 bytes (2.6 MB)
downloaded 2.6 MB

trying URL 'https://cloud.r-project.org/src/contrib/fs_1.3.1.tar.gz'
Content type 'application/x-gzip' length 812680 bytes (793 KB)
downloaded 793 KB

* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
g++  -I"/usr/include/R" -DNDEBUG -I../inst/include/  -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__  -c api.cpp -o api.o
g++  -I"/usr/include/R" -DNDEBUG -I../inst/include/  -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__  -c attributes.cpp -o attributes.o
g++  -I"/usr/include/R" -DNDEBUG -I../inst/include/  -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__  -c barrier.cpp -o barrier.o
g++  -I"/usr/include/R" -DNDEBUG -I../inst/include/  -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__  -c date.cpp -o date.o
g++  -I"/usr/include/R" -DNDEBUG -I../inst/include/  -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__  -c module.cpp -o module.o
g++  -I"/usr/include/R" -DNDEBUG -I../inst/include/  -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__  -c rcpp_init.cpp -o rcpp_init.o
g++ -shared -L/usr/lib/R/lib -Wl,--as-needed -o Rcpp.so api.o attributes.o barrier.o date.o module.o rcpp_init.o -L/usr/lib/R/lib -lR
installing to /usr/lib/R/library/Rcpp/libs
** R
** inst
** byte-compile and prepare package for lazy loading
code for methods in class “C++OverloadedMethods” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “RcppClass” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “RcppClass” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (Rcpp)
* installing *source* package ‘fs’ ...
** package ‘fs’ successfully unpacked and MD5 sums checked
** libs
g++  -I"/usr/include/R" -DNDEBUG -I./libuv/include -I. -pthread -I"/usr/lib/R/library/Rcpp/include" -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__  -c error.cc -o error.o
g++  -I"/usr/include/R" -DNDEBUG -I./libuv/include -I. -pthread -I"/usr/lib/R/library/Rcpp/include" -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__  -c dir.cc -o dir.o
g++  -I"/usr/include/R" -DNDEBUG -I./libuv/include -I. -pthread -I"/usr/lib/R/library/Rcpp/include" -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__  -c fs.cc -o fs.o
g++  -I"/usr/include/R" -DNDEBUG -I./libuv/include -I. -pthread -I"/usr/lib/R/library/Rcpp/include" -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__  -c path.cc -o path.o
g++  -I"/usr/include/R" -DNDEBUG -I./libuv/include -I. -pthread -I"/usr/lib/R/library/Rcpp/include" -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__  -c link.cc -o link.o
g++  -I"/usr/include/R" -DNDEBUG -I./libuv/include -I. -pthread -I"/usr/lib/R/library/Rcpp/include" -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__  -c utils.cc -o utils.o
g++  -I"/usr/include/R" -DNDEBUG -I./libuv/include -I. -pthread -I"/usr/lib/R/library/Rcpp/include" -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__  -c file.cc -o file.o
g++  -I"/usr/include/R" -DNDEBUG -I./libuv/include -I. -pthread -I"/usr/lib/R/library/Rcpp/include" -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__  -c id.cc -o id.o
g++  -I"/usr/include/R" -DNDEBUG -I./libuv/include -I. -pthread -I"/usr/lib/R/library/Rcpp/include" -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__  -c unix/getmode.cc -o unix/getmode.o
g++  -I"/usr/include/R" -DNDEBUG -I./libuv/include -I. -pthread -I"/usr/lib/R/library/Rcpp/include" -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__  -c RcppExports.cpp -o RcppExports.o
gcc -I"/usr/include/R" -DNDEBUG -I./libuv/include -I. -pthread -I"/usr/lib/R/library/Rcpp/include" -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer  -c bsd/setmode.c -o bsd/setmode.o
gcc -I"/usr/include/R" -DNDEBUG -I./libuv/include -I. -pthread -I"/usr/lib/R/library/Rcpp/include" -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer  -c bsd/strmode.c -o bsd/strmode.o
gcc -I"/usr/include/R" -DNDEBUG -I./libuv/include -I. -pthread -I"/usr/lib/R/library/Rcpp/include" -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer  -c bsd/reallocarray.c -o bsd/reallocarray.o
cp -p -f libuv/m4/lt_obsolete.m4 libuv/m4/lt~obsolete.m4
(cd libuv \
	&& touch aclocal.m4 \
	&& touch -r aclocal.m4 configure Makefile.in \
&& CC="gcc" CFLAGS="-Os -fomit-frame-pointer  -fpic -fvisibility=hidden" AR="ar" RANLIB="ranlib" LDFLAGS="-Wl,--as-needed" ./configure --quiet)
make --directory=libuv \
	HAVE_DTRACE=0
make[1]: Entering directory '/tmp/RtmpmkALop/R.INSTALL37478a456a/fs/src/libuv'
 cd . && /bin/sh /tmp/RtmpmkALop/R.INSTALL37478a456a/fs/src/libuv/missing automake-1.14 --foreign
tmp/RtmpmkALop/R.INSTALL37478a456a/fs/src/libuv/missing: line 81: automake-1.14: not found
WARNING: 'automake-1.14' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make[1]: Leaving directory '/tmp/RtmpmkALop/R.INSTALL37478a456a/fs/src/libuv'
make[1]: *** [Makefile:1081: Makefile.in] Error 1
make: *** [Makevars:38: libuv/.libs/libuv.a] Error 2
ERROR: compilation failed for package ‘fs’
* removing ‘/usr/lib/R/library/fs’

The downloaded source packages are in
	‘/tmp/RtmpJfpOpE/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("fs", repos = "https://cloud.r-project.org/") : 
  installation of package ‘fs’ had non-zero exit status
> 
> 
Removing intermediate container 81b39bcecaca
 ---> 8a4319c386c5
Successfully built 8a4319c386c5
```

**Comment by gaborcsardi** [comment]
@bamonroe This is not in the CRAN version of fs yet, only in the devel version.

**Comment by bamonroe** [comment]
Thanks @gaborcsardi, that makes sense. Until it does make its way into CRAN I added to following to my Dockerfile in addition to adding `git` to the `apk add ...` line:
```
RUN R -e 'install.packages("Rcpp", repos="https://cloud.r-project.org/")'
RUN git clone https://github.com/r-lib/fs && R CMD INSTALL fs && rm -rf fs
```

@gaborcsardi did you do something similar?

**Comment by gaborcsardi** [comment]
kind of: https://github.com/r-hub/r-minimal/tree/e38cb0f60dc2804520833e7524bfa33af37686be#known-failures

**Comment by bamonroe** [comment]
Thanks @gaborcsardi, I'm going in a somewhat different direction. Good to see how you handled the issue though.

**Comment by Fazendaaa** [comment]
After reading [this](https://github.com/UBERTC/isl/issues/1) post, my install process proceeded as expect after installing Perl.
